import test from 'node:test';import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
import {createHandler} from '../src/worker.mjs';import {parseRegistration} from '../src/admin.mjs';import {digest} from '../src/security.mjs';
function database(){
 const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('../schema.sql',import.meta.url),'utf8'));sqlite.exec(readFileSync(new URL('../admin-schema.sql',import.meta.url),'utf8'));
 const wrap=(sql,args=[])=>({bind:(...values)=>wrap(sql,values),first:async()=>sqlite.prepare(sql).get(...args)||null,all:async()=>({results:sqlite.prepare(sql).all(...args)}),run:async()=>sqlite.prepare(sql).run(...args)});
 return {prepare:sql=>wrap(sql),batch:async statements=>{sqlite.exec('BEGIN');try{const r=[];for(const s of statements)r.push(await s.run());sqlite.exec('COMMIT');return r;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
}
async function fixture(){
 const env={DB:database(),ACCESS_CODE_PEPPER:'fixture-pepper',ADMIN_ACCESS_KEY:'fixture-owner-key-'.repeat(3),GOOGLE_SERVICE_ACCOUNT_JSON:'injected',DRIVE_ROOT_FOLDER_ID:'root'};
 const storage={authorisedFolder:async folder=>folder==='client-folder',list:async()=>({files:[]})};
 const handler=createHandler({admin:{storage},storage});
 const call=(path,body,cookie,method=body?'POST':'GET',origin='https://gallery.test')=>handler(new Request('https://gallery.test/api/'+path,{method,headers:{Origin:origin,...(body?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})}),env,{waitUntil:p=>p});
 const login=async()=>{const r=await call('admin/session',{key:env.ADMIN_ACCESS_KEY});assert.equal(r.status,200);return r.headers.get('Set-Cookie').split(';')[0];};
 const create=(cookie,extra={})=>call('admin/galleries',{name:'Portraits',client_name:'Client A',email:'client@example.com',folder:'client-folder',confirmed_private:true,allow_downloads:true,expires_at:null,...extra},cookie);
 return {env,call,login,create};
}
test('management fails closed before setup',async()=>{const f=await fixture();delete f.env.ADMIN_ACCESS_KEY;assert.equal((await f.call('admin/overview')).status,503);});
test('anonymous visitor and client session cannot read management data',async()=>{const f=await fixture();assert.equal((await f.call('admin/overview')).status,401);assert.equal((await f.call('admin/overview',null,'__Host-zah_gallery=client')).status,401);assert.equal((await f.call('admin/galleries',{name:'try'})).status,401);});
test('admin login rate limit and secure opaque session',async()=>{const f=await fixture();for(let i=0;i<10;i++)assert.equal((await f.call('admin/session',{key:'bad'})).status,401);assert.equal((await f.call('admin/session',{key:f.env.ADMIN_ACCESS_KEY})).status,429);const g=await fixture();const r=await g.call('admin/session',{key:g.env.ADMIN_ACCESS_KEY});assert.match(r.headers.get('Set-Cookie'),/^__Host-zah_admin=.+; Secure; HttpOnly; SameSite=Strict/);assert.deepEqual(await r.json(),{ok:true});});
test('cross-origin administrator mutations are rejected',async()=>{const f=await fixture();const cookie=await f.login();assert.equal((await f.call('admin/galleries',{name:'try'},cookie,'POST','https://evil.test')).status,403);});
test('management key rotation revokes existing administrator sessions',async()=>{const f=await fixture();const cookie=await f.login();f.env.ADMIN_ACCESS_KEY='different-key-'.repeat(4);assert.equal((await f.call('admin/overview',null,cookie)).status,401);});
test('expired management sessions are denied',async()=>{const f=await fixture();const cookie=await f.login();await f.env.DB.prepare('UPDATE admin_sessions SET expires_at=0').run();assert.equal((await f.call('admin/overview',null,cookie)).status,401);});
test('gallery requires explicit photo confirmation and authorised folder',async()=>{const f=await fixture();const cookie=await f.login();assert.equal((await f.create(cookie,{confirmed_private:false})).status,400);assert.equal((await f.create(cookie,{folder:'root'})).status,400);assert.equal((await f.create(cookie,{email:'invalid'})).status,400);assert.equal((await f.create(cookie,{expires_at:1})).status,400);});
test('created code unlocks only its registered email; code and hash absent from overview',async()=>{const f=await fixture();const cookie=await f.login();const r=await f.create(cookie);assert.equal(r.status,201);const created=await r.json();assert.match(created.code,/^[a-f0-9]{16}\.[A-Za-z0-9_-]{32}$/);assert.equal((await f.call('session',{email:'wrong@example.com',code:created.code})).status,401);assert.equal((await f.call('session',{email:'client@example.com',code:created.code})).status,200);const overview=await(await f.call('admin/overview',null,cookie)).text();assert.ok(!overview.includes(created.code));assert.ok(!overview.includes('access_code_hash'));assert.equal((await f.create(cookie)).status,409);});
test('replacement code invalidates old code and current client sessions',async()=>{const f=await fixture();const admin=await f.login();const g=await(await f.create(admin)).json();const r=await f.call('session',{email:g.email,code:g.code});const client=r.headers.get('Set-Cookie').split(';')[0];const replacement=await(await f.call(`admin/galleries/${g.gallery_id}/rotate`,{},admin)).json();assert.equal((await f.call('gallery',null,client)).status,401);assert.equal((await f.call('session',{email:g.email,code:g.code})).status,401);assert.equal((await f.call('session',{email:g.email,code:replacement.code})).status,200);});
test('disable immediately revokes client sessions',async()=>{const f=await fixture();const admin=await f.login();const g=await(await f.create(admin)).json();const r=await f.call('session',{email:g.email,code:g.code});const client=r.headers.get('Set-Cookie').split(';')[0];assert.equal((await f.call(`admin/galleries/${g.gallery_id}/settings`,{status:'disabled',allow_downloads:false,expires_at:null},admin)).status,200);assert.equal((await f.call('gallery',null,client)).status,401);});
test('admin signout revokes its session',async()=>{const f=await fixture();const cookie=await f.login();assert.equal((await f.call('admin/session',null,cookie,'DELETE')).status,200);assert.equal((await f.call('admin/overview',null,cookie)).status,401);});
test('Jotform parser copies minimal registration fields, never identity photos',()=>{const r=parseRegistration({id:'123',created_at:'date',answers:{1:{type:'control_fullname',answer:{first:'Alex',last:'Example'}},2:{type:'control_email',answer:' ALEX@example.com '},3:{text:'Package code from your receipt',answer:'B1'},4:{type:'control_fileupload',answer:['private-selfie.jpg']}}});assert.deepEqual(r,{submission_id:'123',client_name:'Alex Example',client_email:'alex@example.com',package_code:'B1',registered_at:'date'});assert.equal(parseRegistration({id:'123',answers:{}}),null);});
test('Jotform sync is authenticated, idempotent and separate from granting gallery access',async()=>{const f=await fixture();const cookie=await f.login();f.env.JOTFORM_API_KEY='fixture-api-key';let calls=0;const submission={id:'123',status:'ACTIVE',created_at:'2026-09-30',answers:{1:{type:'control_fullname',prettyFormat:'Alex Example'},2:{type:'control_email',answer:'alex@example.com'}}};const handler=createHandler({admin:{fetcher:async(url,options)=>{calls++;assert.equal(new URL(url).pathname,'/form/262725740128053/submissions');assert.ok(!url.includes(f.env.JOTFORM_API_KEY));assert.equal(options.headers.APIKEY,f.env.JOTFORM_API_KEY);return Response.json({responseCode:200,content:[submission]});}}});const request=()=>new Request('https://gallery.test/api/admin/sync',{method:'POST',headers:{Origin:'https://gallery.test','Content-Type':'application/json',Cookie:cookie},body:'{}'});for(let i=0;i<2;i++)assert.equal((await handler(request(),f.env,{})).status,200);const data=await(await f.call('admin/overview',null,cookie)).json();assert.equal(data.registrations.length,1);assert.equal(data.galleries.length,0);assert.equal(calls,2);});
